PATTERNS = {
    "anli": [
        ("{premise}\n\nBased on the paragraph above can we conclude that \"{hypothesis}\"?", "{answer}"),
        ("{premise}\n\nBased on that paragraph can we conclude that this sentence is true?\n{hypothesis}", "{answer}"),
        ("{premise}\n\nCan we draw the following conclusion?\n{hypothesis}", "{answer}"),
        ("{premise}\nDoes this next sentence follow, given the preceding text?\n{hypothesis}", "{answer}"),
        ("{premise}\nCan we infer the following?\n{hypothesis}", "{answer}"),
        ("Read the following paragraph and determine if the hypothesis is true:\n\n{premise}\n\nHypothesis: {hypothesis}", "{answer}"),
        ("Read the text and determine if the sentence is true:\n\n{premise}\n\nSentence: {hypothesis}", "{answer}"),
        ("Can we draw the following hypothesis from the context? \n\nContext:\n\n{premise}\n\nHypothesis: {hypothesis}", "{answer}"),
        ("Determine if the sentence is true based on the text below:\n{hypothesis}\n\n{premise}", "{answer}"),
        ("Generate a context and a hypothesis.", "Context: {premise}\n\nHypothesis: {hypothesis}"),
    ],

    "common_gen": [
        ("Concepts: {concepts}\n\nWrite a sentence that includes all these words.", "{target}"),
        ("Keywords: {concepts}\n\nWhat is a sentence that includes all these keywords?", "{target}"),
        ("Here are some concepts: {concepts}\n\nWhat is a sentence about these concepts?", "{target}"),
        ("Produce a sentence which mentions all of these concepts: {concepts}", "{target}"),
        ("Write a sentence about the following things:\n\n{concepts}", "{target}"),
        ("Generate a sentence that includes all the following words: {concepts}", "{target}"),
        ("What are the keywords in the following sentence:\n\n{target}", "{concepts}"),
        ("What are the most important words in the following sentence:\n\n{target}", "{concepts}"),
        ("Identify the most salient words in this sentence:\n\n{target}", "{concepts}"),
        ("Generate a sentence, and then tell me the concepts included in that sentence.", "Sentence:\n{target}\n\nConcepts:\n{concepts}"),
    ],

    "xsum": [
        ("Summarize:\n\n{document}", "{summary}"),
        ("Summarize this article:\n\n{document}", "{summary}"),
        ("Summarize this article in one sentence.\n\n{document}", "{summary}"),
        ("{document}\nWhat is a summary of this text?", "{summary}"),
        ("{document}\nWhat was that article about?", "{summary}"),
        ("{document}\n\nThis article was about:", "{summary}"),
        ("Article: {document}\n\nA summary of the above article is?", "{summary}"),
        ("Article: {document}\n\nSummarize the main points of that article.", "{summary}"),
        ("Write an article based on this summary:\n\n{summary}", "{document}"),
        ("Write an article based on this \"{summary}\"", "{document}"),
    ],

    "bool_q": [
        ("{passage}\n\nCan we conclude that {question}?", "{answer}"),
        ("{passage}\n\nIs it true that {question}?", "{answer}"),
        ("{passage}\n\n{question}?", "{answer}"),
        ("Text: {passage}\n\nQuestion: {question}?", "{answer}"),
        ("{passage}\n\nWhat's the best answer to this question: {question}?", "{answer}"),
        ("{passage}\nBased on the above text, what's the best answer to this question: {question}?", "{answer}"),
        ("{passage}\nAnswer this question, making sure that the answer is supposed by the text: {question}?", "{answer}"),
        ("{passage}\n\nIs the following statement correct based on the text\n\n{question}", "{answer}"),
        ("{passage}\n\nIs this statement correct \"{question}\"?", "{answer}"),
        ("Is it true that {question} based on the following text?\n\n{passage}", "{answer}"),
    ],
}